DefaultContentLanguage = "en"

title = "Mokkapps"
baseurl = "https://www.mokkapps.de/"
theme = "prologue"
googleAnalytics = "UA-93160141-1"

[params]
  Description = "Mobile, game & frontend developer. Blogger. Videogame enthusiast. Beekeeper."
  MetaDescription = "Portfolio website from Michael Hoffmann (Mokkapps)"
  DisplayName = "Michael Hoffmann"
  Name = "Michael Hoffmann (Mokkapps)"
  Copyright = "Mokkapps"
  IntroLink = "Intro"
  ProjectsDescription = "An overview of my private software projects:"
  ProjectsButton = "My projects"
  BlogButton = "My blog"
  ProjectsLink = "Projects"
  PublicationsLink = "Publications"
  TalksTitle = "Talks"
  ArticlesTitle = "Articles"
  ResumeLink = "CV"
  AboutMeLink = "About me"
  ContactMeLink = "Contact me"
  BlogLink = "Mokkapps Blog"

[params.Blog]
    Link = "https://www.mokkapps.de/blog"
    Text = "Go to my blog"

[params.NotFound]
  PrimaryText = "Oops, the page you were looking for does not exist."
  SecondaryText = "You could try to navigate to homepage to find the page you were looking for. Alternatively you can send me an email to report any problems."

[params.NotFound.HomePageLink]
    Link = "https://www.mokkapps.de"
    Text = "Go to homepage"

[params.NotFound.ReportLink]
    Link = "mailto:kontakt@mokkapps.de"
    Text = "Report a problem"

[params.Impressum]
  Link = "https://www.mokkapps.de/impressum"
  Text = "Legal notice"

[params.ContactMe]
  Link = "mailto:kontakt@mokkapps.de"
  ButtonText = "Send me an email"

[params.AboutMe]
  Intro = "I am a software developer from the Bavarian Forest and currently live in Munich."
  Spotify = "This is my Spotify playlist which I listen to during programming and sport. It is a crazy mix out of Reggae, Ska, Rock, Hip-Hop, Elektro and more: "

[[params.AboutMe.Statements]]
    Text = "Highly committed, agile personality with broad experience in the field of application development. Experience in working in agile team settings. Delivering excellent results and used to work under pressure."

[[params.AboutMe.Statements]]
    Text = "I am very interested in development of mobile apps, websites and video games. If I am not coding I play videogames or do sports."

[[params.Talks]]
  Link = "https://jambit.com/aktuelles/veranstaltungen/coffeetalks-april-2016/"
  Title = "CoffeeTalk jambit 2016: Unity – Eine Einführung in die Cross-Plattform-Spieleentwicklung"

[[params.Talks]]
  Link = "https://www.jambit.com/en/latest-info/events/coffeetalks-june-2017/"
  Title = "CoffeeTalk jambit 2017: Reactive Programming"

[[params.Talks]]
  Link = "https://www.mokkapps.de/talks/my-first-smartphone-game/"
  Title = "Abendvortrag jambit 2018: Mein erstes Smartphone-Spiel"

[[params.Articles]]
  Link = "https://www.jambit.com/aktuelles/toilet-papers/kotlin-das-bessere-java/"
  Title = "ToiletPaper jambit 2016: Kotlin: Das bessere Java?"

[[params.Articles]]
  Link = "http://ieeexplore.ieee.org/document/7313462/authors?reload=true"
  Title = "Concept for an Intermodal Traveller Information System with Real-Time Data Using Complex Event Processing"

[[params.Articles]]
  Link = "http://www.rebelgamer.de/author/mike"
  Title = "Gaming articles on RebelGamer.de"

[[params.Resume]]
  Link = "https://www.mokkapps.de/cv/Michael_Hoffmann_CV.pdf"
  Title = "PDF version"

[[params.Social]]
  Medium = "twitter"
  Icon = "twitter"
  Link = "https://twitter.com/Mokkapps"

[[params.Social]]
  Medium = "github"
  Icon = "github"
  Link = "https://github.com/Mokkapps"

[[params.Social]]
  Medium = "linkedin"
  Icon = "linkedin"
  Link = "https://www.linkedin.com/in/michael-hoffmann-3b8933b1"

[[params.Social]]
  Medium = "dev"
  Icon = "code"
  Link = "https://dev.to/mokkapps"

[[params.Social]]
  Medium = "email"
  Icon = "envelope"
  Link = "mailto:kontakt@mokkapps.de"

[[params.Project1]]
  Title = "Supermarket Challenge"
  Description = "Used technology: Corona SDK"
  Alt = "Supermarket Challenge"
  Source = "img/supermarket_challenge.png"
  AppStoreImg = "img/app_store.png"
  PlayStoreImg = "img/google_play.png"
  PlayStoreUrl = "https://play.google.com/store/apps/details?id=de.mokkapps.supermarketchallenge"
  AppStoreUrl = "https://itunes.apple.com/de/app/supermarket-challenge/id1207665675"

[[params.Project2]]
  Title = "RebelGamer Mobile App"
  Description = "Used technology: React Native"
  Alt = "RebelGamer"
  Source = "img/rebelgamer.png"
  Url = "https://github.com/Mokkapps/rebelgamer-mobile-app"
  AppStoreImg = "img/app_store.png"
  PlayStoreImg = "img/google_play.png"
  PlayStoreUrl = "https://play.google.com/store/apps/details?id=de.rebelgamer.RebelGamerRSS"
  AppStoreUrl = "https://itunes.apple.com/de/app/rebelgamer-news-fur-gamer/id1187403828"

[[params.Project3]]
  Title = "Scrum Standup Picker"
  Description = "Used technologies: Angular 5, Electron"
  Alt = "Scrum Standup Picker"
  Source = "img/standup_picker.jpg"
  Url = "https://github.com/Mokkapps/scrum-daily-standup-picker"

[[params.SideProjects]]
  Title = "Blockchain Honey Shop"
  Url = "https://github.com/Mokkapps/blockchain-honey-shop"

[[params.SideProjects]]
  Title = "VS Code Extension: Jasmine Test Selector"
  Url = "https://github.com/Mokkapps/jasmine-test-selector"

[[params.SideProjects]]
  Title = "npm package: GitHub Traffic CLI"
  Url = "https://github.com/Mokkapps/github-traffic-cli"

[[params.SideProjects]]
  Title = "WordPress Website: Imkerei Hoffmann"
  Url = "http://hoffmann-imkerei.de/"